-- Create todos table
CREATE TABLE public.todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task text NOT NULL,
  completed boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Add comments
COMMENT ON TABLE public.todos IS 'A simple todo list application table';
COMMENT ON COLUMN public.todos.id IS 'Unique identifier for each todo item';
COMMENT ON COLUMN public.todos.task IS 'The task description or title';
COMMENT ON COLUMN public.todos.completed IS 'Whether the task has been completed';
COMMENT ON COLUMN public.todos.created_at IS 'Timestamp when the todo was created';

-- Create indexes for better performance
CREATE INDEX idx_todos_created_at ON public.todos(created_at DESC);
CREATE INDEX idx_todos_completed ON public.todos(completed);

-- Enable RLS (Row Level Security)
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
